# Generated by Django 5.1 on 2024-08-16 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_vote_who_create'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voteanswer',
            unique_together={('option', 'user')},
        ),
    ]
