# Generated by Django 5.1 on 2024-08-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_questionansweroption_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionansweroption',
            unique_together=set(),
        ),
    ]
